# -*- coding: utf-8 -*-
{
    'name': "Invoice and ProForma Invoice Reports For India",
    'category': 'Report',
    'version': '17.0.2.1',
    'summary': 'Invoice and ProForma Invoice Reports For India',
    'description': """Invoice and ProForma Invoice Reports For India""",
    'license': 'OPL-1',
    "author": "BrowseInfo",
    'website': 'https://www.browseinfo.in',
    'depends': ['base','account','sale', 'sale_management', 'isha_auto_invoice', 'l10n_in', 'esign_invoice',
                'isha_asset_management','isha_advance_request','isha_department_access', 'picking_print_hub','isha_api_integration'],
    'data': [
        'security/ir.model.access.csv',
        'report/isha_invoice_company_details.xml',
        'report/invoice_report_templates.xml',
        'report/invoice_reports.xml',
        'report/isha_custom_report.xml',
        'report/proforma_invoice_custom.xml',
        'report/invoice_print_template.xml',
        'report/payment_report.xml',
        'report/inherit_payment_printout.xml',
        'report/journal_report.xml',
        'views/account_move.xml',
        # 'report/pick_list_template.xml',
    ],
    'installable': True,
    'auto_install': False,
}
